### ISSUE TITLE
correction to the solution?

### ISSUE THREAD

**Issue by nicole-roach-data** [learn-co-curriculum/dsc-pca-in-scikitlearn-lab#1]
features = ['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# Create features and Target dataset
from sklearn.preprocessing import StandardScaler
X = df.loc[:, features].values
y = df.loc[:,'Target'].values

the solutions branch should be corrected I believe to reflect the above.

**Comment by lmcm18** [comment]
Fixed.
